[General]

Font="LiterationMono Nerd Font Propo"
FontSize="12"
RoundCorners="20"

# Quotes Component
Quote=""
QuoteColor=#ffffff
QuoteFontSize=16

# DateTime Component
DateTimeColor=#ffffff
DateFontSize=16
TimeFontSize=90


UserProfilePicture="Shiboing/levi_pfp.png"

#################### Background ####################

Background="Shiboing/JapanAlley.png"

#################### Colors ####################

DimBackgroundColor="#000000"

PasswordFieldBackgroundColor="#222222"
PasswordFieldTextColor="#ffffff"
PasswordIconColor="#aaaaaa"

PlaceholderTextColor="#666666"
WarningColor="#ffffff"

LoginButtonTextColor="#ffffff"
LoginButtonBackgroundColor="#333333"
SessionButtonTextColor="#aaaaaa"

DropdownTextColor="#000000"
DropdownSelectedBackgroundColor="#ffffff"
DropdownBackgroundColor="#ffffff"

HighlightBorderColor="#ffffff"

HoverPasswordIconColor="#ffffff"
HoverSessionButtonTextColor="#ffffff"




#################### Interface Behavior ####################

ForceLastUser="true"
PasswordFocus="true"
HideCompletePassword="true"
AllowEmptyPassword="false"
AllowUppercaseLettersInUsernames="false"
BypassSystemButtonsChecks="false"
